

DELETE FROM ENGEMAN.CFGUSR WHERE NOME IN (

SELECT CFGUSR.nome
FROM ENGEMAN.CFGUSR 
INNER JOIN ENGEMAN.USRXEMP ON USRXEMP.NOME=CFGUSR.NOME
WHERE NOMEGRUPO = 'SOLICITANTES' AND USRXEMP.CODFUN NOT IN (SELECT DISTINCT CODFUN FROM ENGEMAN.SOLICITACAO)
)


DELETE FROM ENGEMAN.FUNC WHERE CODFUN IN (

SELECT func.codfun
FROM ENGEMAN.FUNC 
INNER JOIN ENGEMAN.USRXEMP ON USRXEMP.CODFUN=FUNC.CODFUN
INNER JOIN ENGEMAN.CFGUSR ON USRXEMP.NOME=CFGUSR.NOME
WHERE NOMEGRUPO = 'SOLICITANTES' AND USRXEMP.CODFUN NOT IN (SELECT DISTINCT CODFUN FROM ENGEMAN.SOLICITACAO)

)