INSERT INTO ENGEMAN.ENGEMAN.CFGUSR 
(ACESSSYNC,ALACONTAV,ALACONTV,ALAEST,ALASLA,ALASOL,ALERTA_FUNC_PREVISTO,ALERTA_SERV_NAO_EXEC,ALERTAFLUXOBLOQ,ALERTAFLUXOPEND
	,ALTERAR,ASSDAT,ATIVO,AUTENTICAR,AUTOINSERT,AUTOSAVE,BACKGROUNDCOLOR,CODCFGUSRGRUPO,CODCLI,CODFOR,CONFSYNC,CONTA,CORAJUDA,DATALT,DATALTSEN
	,DIASEXP,EDITARUSR,ENTERTAB,EXCLUIR,EXIBIR_TAREFAS,EXIBIRAJUDA,EXIBIRBARRA,EXIBIRMENU,EXIBIRTAGREL,F3,FILTRAR_ATIVOS,GUIADEST,IGNORAGRUPO
	,INCLUIR,INTERCONTAV,INTERCONTV,INTERVALO,INTERVALOEST,INTERVALOSLA,LARGURAMAX,LINGUAGEM,LOGINSIMPLES,MANTERTELA,MASTER,MULTIACESSOS,NEWMSG
	,NOME,NOMEALT,NOMEGRUPO,OPCAOSALVARSENHA,PERMITETROCA,PORTA,POSTELA,RECMAILFLUXO,REGMAX,REPOSICIONAR,RETORNO,SENHA,SENHAM,SHOWAPLICTREE
	,SMTP,SOL_IMPRIMIR,TEMPALERTAFLUXOBLOQ,TEMPALERTAFLUXOPEND,TEMPDELAY,TEMPSHOW,TENTATIVAS,TIMEOUT,TIPO,TIPOALA,TIPOALACONT,TIPOALAEST,TIPOALASLA
	,TIPOALERTAFLUXO,TROCASENHA,ULTACESSOCS,ULTACESSOSSW,ULTACESSOWEB,VISUGRID,ALASLAMAIL,INTERVALOSLAMAIL,ALACONTAVMAIL,ALACONTVMAIL,TIPOALACONTAV
	,INTERCONTAVMAIL,INTERCONTVMAIL,U_FECHARSE,U_CADOCOR,U_NIVELAPR,U_NIVEL,U_USUADM,U_GEREHE,U_APROVAPA,U_APROVHE,U_APRAES,U_CADAPA,U_CADRSE,U_FECHACAN,U_APRPES,U_GERA
)


SELECT  
ACESSSYNC,ALACONTAV,ALACONTV,ALAEST,ALASLA,ALASOL,ALERTA_FUNC_PREVISTO,ALERTA_SERV_NAO_EXEC,ALERTAFLUXOBLOQ,ALERTAFLUXOPEND
	,ALTERAR,ASSDAT,ATIVO,AUTENTICAR,AUTOINSERT,AUTOSAVE,BACKGROUNDCOLOR,CODCFGUSRGRUPO,CODCLI,CODFOR,CONFSYNC,CONTA,CORAJUDA,DATALT,DATALTSEN
	,DIASEXP,EDITARUSR,ENTERTAB,EXCLUIR,EXIBIR_TAREFAS,EXIBIRAJUDA,EXIBIRBARRA,EXIBIRMENU,EXIBIRTAGREL,F3,FILTRAR_ATIVOS,GUIADEST,IGNORAGRUPO
	,INCLUIR,INTERCONTAV,INTERCONTV,INTERVALO,INTERVALOEST,INTERVALOSLA,LARGURAMAX,LINGUAGEM,LOGINSIMPLES,MANTERTELA,MASTER,MULTIACESSOS,NEWMSG
	,X.TEXTO,NOMEALT,NOMEGRUPO,OPCAOSALVARSENHA,PERMITETROCA,PORTA,POSTELA,RECMAILFLUXO,REGMAX,REPOSICIONAR,RETORNO,SENHA,SENHAM,SHOWAPLICTREE
	,SMTP,SOL_IMPRIMIR,TEMPALERTAFLUXOBLOQ,TEMPALERTAFLUXOPEND,TEMPDELAY,TEMPSHOW,TENTATIVAS,TIMEOUT,TIPO,TIPOALA,TIPOALACONT,TIPOALAEST,TIPOALASLA
	,TIPOALERTAFLUXO,TROCASENHA,ULTACESSOCS,ULTACESSOSSW,ULTACESSOWEB,VISUGRID,ALASLAMAIL,INTERVALOSLAMAIL,ALACONTAVMAIL,ALACONTVMAIL,TIPOALACONTAV
	,INTERCONTAVMAIL,INTERCONTVMAIL,U_FECHARSE,U_CADOCOR,U_NIVELAPR,U_NIVEL,U_USUADM,U_GEREHE,U_APROVAPA,U_APROVHE,U_APRAES,U_CADAPA,U_CADRSE,U_FECHACAN,U_APRPES,U_GERA
--X.TEXTO, NOME
 FROM ENGEMAN.ENGEMAN.CFGUSR
INNER JOIN (SELECT U_TEXTO TEXTO FROM ENGEMAN_TESTE.ENGEMAN.USER_TEMP) X ON 2=2 
  
 
 WHERE NOME NOT IN (SELECT U_TEXTO FROM ENGEMAN_TESTE.ENGEMAN.USER_TEMP)
 --AND X.TEXTO NOT IN (SELECT NOME FROM ENGEMAN_TESTE.ENGEMAN.CFGUSR)
 AND NOME='MODELO' 
 AND NOME NOT IN (SELECT NOME FROM ENGEMAN.ENGEMAN.CFGUSR WHERE NOME <> 'MODELO')