SELECT 'DENY SELECT, INSERT, DELETE, UPDATE ON "' + TABLE_SCHEMA + '"."' + TABLE_NAME + '" TO "SAP"' 
FROM information_schema.tables
WHERE TABLE_NAME NOT IN ('MATERIAL', 'MOEDA', 'UNIDADE', 'GRUMAT', 'CLAMAT', 'ALMOX', 'LOCMATER','ESTOQUE')