--SUPERVISOR DUPLO JOIN

LEFT JOIN (SELECT U_PK_REDUZIDO ID
                , USER_SUPER.U_DESC 
                , USER_SUPER.R_FUNC_CODFUN CODFUNSUPERV
                , USER_SUPER.R_FUNC_CODFUN_1 CODFUNGER
                , USER_SUPER.R_FUNC_CODFUN_2 CODFUNSUPERI
                , USER_SUPER.R_CONTABIL_CODCON CODCON
                , CONTABIL.TAG AREA
                , CASE WHEN CONTABIL.TAG='AEG' THEN F2.CODFIL ELSE F1.CODFIL END CODFIL
                , CASE WHEN CONTABIL.TAG='AEG' THEN  F2.TAG ELSE F1.TAG END TAGFIL
                , SUPERV.NOME NOMESUPERV
                , GEREN.NOME NOMEGER
                , SUPERINT.NOME NOMESUPERI
            FROM USER_SUPER
            INNER JOIN CONTABIL ON CONTABIL.CODCON = USER_SUPER.R_CONTABIL_CODCON
            LEFT JOIN FILIAL F1 ON F1.R_USER_SUPER_U_PK_REDUZIDO = USER_SUPER.U_PK_REDUZIDO
            LEFT JOIN FILIAL F2 ON F2.R_USER_SUPER_U_PK_REDUZIDO_1 = USER_SUPER.U_PK_REDUZIDO
            LEFT JOIN FUNC SUPERV ON SUPERV.CODFUN=USER_SUPER.R_FUNC_CODFUN
            LEFT JOIN FUNC GEREN ON GEREN.CODFUN=USER_SUPER.R_FUNC_CODFUN_1
            LEFT JOIN FUNC SUPERINT ON SUPERINT.CODFUN=USER_SUPER.R_FUNC_CODFUN_2
          ) SUPER ON SUPER.CODCON = APLIC.CODCON
		  
		  

 LEFT JOIN (SELECT U_PK_REDUZIDO ID
                , USER_SUPER.U_DESC 
                , USER_SUPER.R_FUNC_CODFUN CODFUNSUPERV
                , USER_SUPER.R_FUNC_CODFUN_1 CODFUNGER
                , USER_SUPER.R_FUNC_CODFUN_2 CODFUNSUPERI
                , USER_SUPER.R_CONTABIL_CODCON CODCON
                , CONTABIL.TAG AREA
                , CASE WHEN CONTABIL.TAG='AEG' THEN F2.CODFIL ELSE F1.CODFIL END CODFIL
                , CASE WHEN CONTABIL.TAG='AEG' THEN  F2.TAG ELSE F1.TAG END TAGFIL
                , SUPERV.NOME NOMESUPERV
                , GEREN.NOME NOMEGER
                , SUPERINT.NOME NOMESUPERI
            FROM USER_SUPER
            INNER JOIN CONTABIL ON CONTABIL.CODCON = USER_SUPER.R_CONTABIL_CODCON
            LEFT JOIN FILIAL F1 ON F1.R_USER_SUPER_U_PK_REDUZIDO = USER_SUPER.U_PK_REDUZIDO
            LEFT JOIN FILIAL F2 ON F2.R_USER_SUPER_U_PK_REDUZIDO_1 = USER_SUPER.U_PK_REDUZIDO
            LEFT JOIN FUNC SUPERV ON SUPERV.CODFUN=USER_SUPER.R_FUNC_CODFUN
            LEFT JOIN FUNC GEREN ON GEREN.CODFUN=USER_SUPER.R_FUNC_CODFUN_1
            LEFT JOIN FUNC SUPERINT ON SUPERINT.CODFUN=USER_SUPER.R_FUNC_CODFUN_2
          ) USER_SUPER ON USER_SUPER.CODCON = APLIC.CODCON